### ISSUE TITLE
parse error: unexpected @

### ISSUE THREAD

**Issue by MrKong121** [GarbajYT/godot_updated_fps_controller#5]
No idea what I'm doing wrong here but for some reason, it doesn't seem to like having @ before every "onready"
this is my first time trying to make a game so its to be expected that I would run into a couple of errors so any help would be appreciated

**Comment by GarbajYT** [comment]
@onready will only work in Godot 4.0 and above. If you are using a 3.x version of godot, use the 3.3 version

**Comment by MrKong121** [comment]
I'm kicking myself I didn't even bother to check my version that's literally all I had to do
